# - name: apt install postgres and python
#   become: yes
#   apt:
#     state: latest
#     update_cache: yes
#     cache_valid_time: 3600
#     pkg:
#     - postgresql
#     - libpq-dev
#     - postgresql-client
#     - postgresql-client-common
#     - python3
#     - python3-pip

# - name: pip install psycopg2
#   pip:
#     name: psycopg2

# - name: configure postgresql.conf
#   become: yes
#   blockinfile:
#     path: "/etc/postgresql/11/main/postgresql.conf"
#     block: |
#       listen_addresses = '*'
#     marker: "# {mark} ANSIBLE MANAGED BLOCK postgresqlconf"

# - name: configure pg_hba.conf
#   become: yes
#   blockinfile:
#     path: "/etc/postgresql/11/main/pg_hba.conf"
#     block: |
#       host    all             all             0.0.0.0/0            md5
#     marker: "# {mark} ANSIBLE MANAGED BLOCK pg_hba"

# - name: Restart service postgresql, in all cases
#   systemd:
#     name: postgresql
#     state: restarted


# - name: create 
#   community.general.postgresql_user:
#     name: airflow
#     password: poilkj09
#     role_attr_flags: CREATEDB,CREATEROLE,SUPERUSER
#     expires: infinity

# - name: Create a new database with name "acme" and specific encoding and locale # settings.
#   community.general.postgresql_db:
#     name: airflow
#     encoding: UTF-8
#     lc_collate: en_US.UTF-8
#     lc_ctype: en_US.UTF-8
#     template: template0