# - name: remove hostname
#   become: yes
#   file:
#     state: absent
#     path: /etc/hostname

# - name: set hostname
#   become: yes
#   lineinfile:
#     create: yes
#     dest: /etc/hostname
#     regexp: '{{ inventory_hostname }}$'
#     line: "{{ inventory_hostname }}"
#     state: present

- name: hostname template
  become: yes
  template:
    src: hostname.j2
    dest: /etc/hostname

- name: Add the inventory into /etc/hosts
  become: yes
  lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ item }}$'
    line: "{{ hostvars[item]['ansible_default_ipv4']['address'] }} {{item}}"
    state: present
  when: hostvars[item]['ansible_facts']['default_ipv4'] is defined
  with_items:
    - "{{ groups['all'] }}"
