all:
  # hosts:
  #   ungrouped: orphan_ip
  vars:
    ansible_python_interpreter: /usr/bin/python3
  children:
    local:
      hosts:
        localhost:
          ansible_host: 127.0.0.1
          ansible_connection: local
    pi:
      hosts:
        pi1:
          ansible_host: 192.168.178.44
        pi2:
          ansible_host: 192.168.178.52
        pi3:
          ansible_host: 192.168.178.53
    webservers:
      hosts:
        pi2:
    database:
      hosts:
        pi1:
    jenkins_master:
      hosts:
        pi2:
    jenkins_agent:
      hosts:
        pi[1:4]:
    hadoop:
      hosts:
        pi[1:2]:
    dev:
      hosts:
        pi2: